version: 3.8.0
services:
  myfinance-application:
    image: myfinance-application
    container_name: myfinance-application
    build:
      context: ./
      dockerfile: ./MyFinanceWeb.Web/Dockerfile
    depends_on:
      - myfinance-database
    environment:
      - PORT=5000
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:5000
    networks:
      - myfinance-networks

  myfinance-database:
    image: myfinance-database
    container_name: myfinance-database
    build:
      context: ./MyFinanceWeb.Infra.Data
      dockerfile: Dockerfile
    environment:
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=Password@12345
      - ACCEPT_EULA=Y

    volumes:
      - ./MyFinanceWeb.Infra.Data/Database/data:/var/opt/mssql/data
      - ./MyFinanceWeb.Infra.Data/Database/log:/var/opt/mssql/log
      - ./MyFinanceWeb.Infra.Data/Database/secrets:/var/opt/mssql/secrets
    networks:
      - myfinance-networks
    ports:
      - 1435:1433

networks:
  myfinance-networks:
    name: myfinance-networks
